name: Coveralls
\n
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
\n
jobs:
  coveralls:
\n
    runs-on: ubuntu-latest
\n
    steps:
    - name: Cloning repo
      uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Installing dependencies
      run: npm install
    - name: Generating coverage information
      run: npm run coveralls
    - name: Coveralls GitHub Actions
      uses: coverallsapp/github-action@master
      with: 
